#!/bin/sh 
# This is a tool to coordinate all the subprocesses that are required
# to build the language
#    source -> qbe -> asm -> o
# Eventually this will be rolled into the ocaml source but for now its
# alot easier to coordinate it in this shell script

if [ "${COMPY_AUX_DEBUG:-0}" -eq 1 ]
then
    set -x
fi

SCRIPTROOT="$(cd $(dirname $0) && pwd)"

: "${COMPY_C:=$SCRIPTROOT/_build/default/compy_c.exe}"
: "${QBE:=/home/wharding/opt/bin/qbe}"
: "${AS:=as}"
: "${LD:=gcc}"


cmd=$1
shift

bail() {
    echo $2
    exit $1
}

case $cmd in
    compile)
	src=$1
	base="$src"
	#echo base=$base
	#mkdir -p $(dirname "$build_dir/$base") || true
	$COMPY_C $src -o $base.q  || bail 1 "Compy failed..."
	$QBE $base.q -o $base.S || bail 2 "QBE Failed..."
	$AS $base.S -o $base.o || bail 3 "AS failed..."
	$LD $base.o -o $base.exe || bail 4 "LD failed..."
	;;
    check)
	err=""
	which $QBE >/dev/null || err="$err\nCant find qbe"
	which $AS  >/dev/null || err="$err\nCant find as"
	which $LD  >/dev/null || err="$err\nCant find ld" 

	#echo compy=$COMPY_C
	#echo qbe=$QBE
	#echo as=$AS
	#echo ld=$LD

	if [ ! -z "$err" ]; then
	    echo "$err"
	    exit 200
	fi
	;;
    *)
	echo "compy-aux: Bad command: $cmd"
	exit 99
	;;
esac
